# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/Oppla-AI/oppla/discussions/new/choose
    about: To request a feature, open a new Discussion in one of the appropriate Discussion categories
  - name: "Oppla Discord"
    url: https://discord.gg/KZJD9WqCkS
    about: Real-time discussion and user support